FROM eclipse-temurin:21-jre
RUN apt-get update && \
    apt-get install -y stockfish zstd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY deploy/chessonline-backend.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
